# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Account.create(company_name: 'Hang Fire Smoke House Co', primary_contact: 'Shauna Guinn', email: 'hangfirebbq@gmail.com', phone:'07803293552')
Restaurant.create(account_id: '1', name: 'Hang Fire Southern Kitchen', location: 'Pump House, Barry', website: 'hangfirebbq.com', primary_contact: 'Sam Evans', email: 'hangfirebbq@gmail.com', phone:'07803293552')
Rdetail.create(restaurant_id: '1', booking_duration: '2', min_booking: '1', max_booking: '10', max_diners_at_current_time: '23', max_current_diners: '48', current_diners_window_start: '90', current_diners_window_end: '45', big_table_count: '2', large_table_count: '4', safe_float: 1000, till_float_main: 200, till_float_bar: 100, eve_full_diners: 50, day_full_diners: 110, afternoon_full_diners: 50)
Error.create(ref: '999999101', msg: 'Please enter all required information.', desc: 'Validation - Booking enquiry : Check all fields have been entered.')
Error.create(ref: '999999102', msg: 'Bookings can only be made for today or future dates, please amend date and try again.', desc: 'Validation - Booking enquiry : Check booking not in the past.')
Error.create(ref: '999999103', msg: 'The restaurant is closed on Mondays and Tuesdays, please amend date and try again.', desc: 'Validation - Booking enquiry : Check booking not made when restaurant is closed.')
Error.create(ref: '999999104', msg: 'The restaurant opens at 5pm on this day, please amend booking time and try again.', desc: 'Validation - Booking enquiry : User tried to book outside opening hours on Wed, Thurs, Fri.')
Error.create(ref: '999999105', msg: 'The last booking time for a Sunday is 3pm, please amend your booking time and try again.', desc: 'Validation - Booking enquiry : User tried to book outside food serve hours on Sun.')
Error.create(ref: '999999106', msg: 'Unfortunately we are fully booked at this time.', desc: 'Validation - Booking enquiry : Cannot accomodate due to volume of current diners or diners at same time.')
Error.create(ref: '999999107', msg: 'Sorry but there is no availability for a table of this size on this date.', desc: 'Validation - Booking enquiry. Cannot accommodate more than PARAM-MAX big parties of PARAM-BIG size.')
Error.create(ref: '999999108', msg: 'Sorry but there is no availability for a table of this size on this date.', desc: 'Validation - Booking enquiry. Cannot accommodate more than PARAM-MAX large parties of PARAM-LARGE size.')
Error.create(ref: '999999109', msg: 'Sorry, there has been a system error. Please re-try.', desc: 'Validation - Booking enquiry. Non-specific fault, system error.')
Error.create(ref: '999999110', msg: 'We are fully booked at your requested time, but we do have a table 15 mins earlier.', desc: 'Confirmation - Booking Enquiry - Table available 15 mins earlier.')
Error.create(ref: '999999111', msg: 'We are fully booked at your requested time, but we do have a table 15 mins later.', desc: 'Confirmation - Booking Enquiry - Table available 15 mins later.')
Error.create(ref: '999999112', msg: 'Online bookings cannot be made for same day.', desc: 'Validation - Booking enquiry Booking for today cannot be made online.')
Error.create(ref: '999999113', msg: 'The information you have entered does not match your booking, please try again or get in touch via our website form.', desc: 'Error given when customer tries to cancel booking but information given doesnot match booking phone or email.')
Error.create(ref: '999999114', msg: 'Please enter phone number OR email used to confirm this booking. Your booking has not been cancelled.', desc: 'Error given when user tries to cancel a booking but has not entered any data.')
Error.create(ref: '999999115', msg: 'The restaurant does not open until March 9th, 2016. Please try to book after this date.', desc: 'Customer tried to book before March 9th 2016.')
Error.create(ref: '999999116', msg: 'We cannot accomodate your party at this time, please check food service hours.', desc: 'Validation - Booking enquiry : Cannot accommodate as between 2 and 5 on Saturday.')
Error.create(ref: '999999117', msg: 'We are sorry but the latest time for table booking is 9pm, please try again for an earlier time.', desc: 'Validation - Customer tried to book at 9.30 on any day.')
Error.create(ref: '999999118', msg: 'Unfortunately we are fully booked at this time.', desc: 'Generic error when any booking parameters are met. Simplified message.')
Error.create(ref: '999999119', msg: 'The latest booking time for groups 7+ is 8pm, please try booking at an earlier time.', desc: 'Larger groups need to come before 8.30pm to allow time to feed them.')
Error.create(ref: '999999120', msg: 'Bookings of 5 or more in December cannot be made online. Please email hangfirebarry@gmail.com with your booking request.', desc: 'December booking error - cannot be online.')
Error.create(ref: '999999121', msg: 'The latest booking time for Friday and Saturday lunch groups 7+ is 1.30pm, please try booking at an earlier time.', desc: 'Fri/Sat Lunch - Larger groups need to come before 2pm to allow time to feed them.')
Error.create(ref: '999999122', msg: 'The latest booking time for Sunday lunch groups 7+ is 2.30pm, please try booking at an earlier time.', desc: 'Sun Lunch - Larger groups need to come before 3pm to allow time to feed them.')
Error.create(ref: '999999123', msg: 'We are currently not taking bookings for this date.', desc: 'When customer tries to book at a date in the future not currently released.')
Error.create(ref: '999999124', msg: 'We are sorry but from Jan 2018, the largest group we can accommodate is 10.', desc: 'From Jan 2018 no longer taking tables of 12. Temp error should not be needed once we can remove the 12 from the list.')