# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Staff.create(name: 'David Beer', status: 'Active', area: 'Kitchen', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Kyle Mackenzie', status: 'Active', area: 'Kitchen', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Marius-Tiberiu Cristoiu', status: 'Active', area: 'Kitchen', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Perrie Morson', status: 'Active', area: 'Kitchen', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Tomasz Posieczek', status: 'Active', area: 'Kitchen', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Evan Morgan', status: 'Active', area: 'Kitchen', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Cameron Macallister', status: 'Active', area: 'Kitchen', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'James Scott', status: 'Active', area: 'Kitchen', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Caitlin Hollman', status: 'Active', area: 'Front of House', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Carla Burrows', status: 'Active', area: 'Front of House', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Dom Giliat', status: 'Active', area: 'Front of House', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Gemma Hocking', status: 'Active', area: 'Front of House', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Holly Lashar', status: 'Active', area: 'Front of House', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Sarah Leanarts', status: 'Active', area: 'Front of House', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Sophie Burrows', status: 'Active', area: 'Front of House', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Mark Sedgewick', status: 'Active', area: 'Front of House', payment_terms:'Hourly Rate', job_title: '')
Staff.create(name: 'Craig Allen', status: 'Active', area: 'Front of House', payment_terms:'Salaried', job_title: '')
Staff.create(name: 'Joshua Cowley', status: 'Active', area: 'Front of House', payment_terms:'Salaried', job_title: '')
Staff.create(name: 'Mike St Amand', status: 'Active', area: 'Kitchen', payment_terms:'Salaried', job_title: '')
Staff.create(name: 'Angharad Challoner', status: 'Active', area: 'Kitchen', payment_terms:'Salaried', job_title: '')
Staff.create(name: 'Jon Whittaker', status: 'Active', area: 'Kitchen', payment_terms:'Salaried', job_title: '')
Staff.create(name: 'Kieren Myers', status: 'Active', area: 'Kitchen', payment_terms:'Salaried', job_title: '')
Staff.create(name: 'Sam Rees', status: 'Active', area: 'Kitchen', payment_terms:'Salaried', job_title: '')
Staff.create(name: 'Tomas Blanco', status: 'Active', area: 'Kitchen', payment_terms:'Salaried', job_title: '')
Accruel_rate.create(rate: 0.1207, effective_date:"01-01-2019")
Tronc.create(start_date: "01-10-2019", end_date: "31-12-2019", status:"Current", foh_split: 60.0, kitchen_split: 40.0)
Tronc.create(start_date: "01-07-2019", end_date: "30-09-2019", status:"Completed", foh_split: 60.0, kitchen_split: 40.0)