require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StaffhoursController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Staffhour. As you add validations to Staffhour, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StaffhoursController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all staffhours as @staffhours" do
      staffhour = Staffhour.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:staffhours)).to eq([staffhour])
    end
  end

  describe "GET show" do
    it "assigns the requested staffhour as @staffhour" do
      staffhour = Staffhour.create! valid_attributes
      get :show, {:id => staffhour.to_param}, valid_session
      expect(assigns(:staffhour)).to eq(staffhour)
    end
  end

  describe "GET new" do
    it "assigns a new staffhour as @staffhour" do
      get :new, {}, valid_session
      expect(assigns(:staffhour)).to be_a_new(Staffhour)
    end
  end

  describe "GET edit" do
    it "assigns the requested staffhour as @staffhour" do
      staffhour = Staffhour.create! valid_attributes
      get :edit, {:id => staffhour.to_param}, valid_session
      expect(assigns(:staffhour)).to eq(staffhour)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Staffhour" do
        expect {
          post :create, {:staffhour => valid_attributes}, valid_session
        }.to change(Staffhour, :count).by(1)
      end

      it "assigns a newly created staffhour as @staffhour" do
        post :create, {:staffhour => valid_attributes}, valid_session
        expect(assigns(:staffhour)).to be_a(Staffhour)
        expect(assigns(:staffhour)).to be_persisted
      end

      it "redirects to the created staffhour" do
        post :create, {:staffhour => valid_attributes}, valid_session
        expect(response).to redirect_to(Staffhour.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved staffhour as @staffhour" do
        post :create, {:staffhour => invalid_attributes}, valid_session
        expect(assigns(:staffhour)).to be_a_new(Staffhour)
      end

      it "re-renders the 'new' template" do
        post :create, {:staffhour => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested staffhour" do
        staffhour = Staffhour.create! valid_attributes
        put :update, {:id => staffhour.to_param, :staffhour => new_attributes}, valid_session
        staffhour.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested staffhour as @staffhour" do
        staffhour = Staffhour.create! valid_attributes
        put :update, {:id => staffhour.to_param, :staffhour => valid_attributes}, valid_session
        expect(assigns(:staffhour)).to eq(staffhour)
      end

      it "redirects to the staffhour" do
        staffhour = Staffhour.create! valid_attributes
        put :update, {:id => staffhour.to_param, :staffhour => valid_attributes}, valid_session
        expect(response).to redirect_to(staffhour)
      end
    end

    describe "with invalid params" do
      it "assigns the staffhour as @staffhour" do
        staffhour = Staffhour.create! valid_attributes
        put :update, {:id => staffhour.to_param, :staffhour => invalid_attributes}, valid_session
        expect(assigns(:staffhour)).to eq(staffhour)
      end

      it "re-renders the 'edit' template" do
        staffhour = Staffhour.create! valid_attributes
        put :update, {:id => staffhour.to_param, :staffhour => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested staffhour" do
      staffhour = Staffhour.create! valid_attributes
      expect {
        delete :destroy, {:id => staffhour.to_param}, valid_session
      }.to change(Staffhour, :count).by(-1)
    end

    it "redirects to the staffhours list" do
      staffhour = Staffhour.create! valid_attributes
      delete :destroy, {:id => staffhour.to_param}, valid_session
      expect(response).to redirect_to(staffhours_url)
    end
  end

end
